sudo: required
services:
  - docker

before_install:
  - docker build -t miloofcroton/docker-test -f Dockerfile.dev .

script:
  - docker run -e "CI=true" miloofcroton/docker-test npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-us-west-2-484708856895"
  bucket_path: "docker-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

