sudo: required
services:
  - docker

before_install:
  - docker build -t miloofcroton/docker-test -f Dockerfile.dev .

script:
  - docker run miloofcroton/docker-test set CI=true&&npm run test -- --coverage

